
spring:
  datasource:
    url: jdbc:postgresql://ep-empty-river-ad7lhqyj-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_cdJx1WMZ4lyP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
