
spring:
  datasource:
    url: jdbc:postgresql://ep-withered-sky-a1mchkqx-pooler.ap-southeast-1.aws.neon.tech/candidat?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_lXfYtCk6ns5F
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
