spring:
  datasource:
    url: jdbc:mysql://localhost:3306/water?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


